import { readFile, writeFile, readdir, rename } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { instrumentGuidanceSource, scanGuidanceSource } from './guidance-source.js';
import type { GuidanceDefinition } from '../src/guidance-catalog.js';
import { MCPVAULT_SERVER_INSTRUCTIONS } from '../src/wiki-policy.js';

const write = process.argv.includes('--write'), check = process.argv.includes('--check');
const files = (await readdir('src')).filter(f => f.endsWith('.ts') && !f.endsWith('.test.ts') && !f.startsWith('guidance-')).sort();
const definitions = new Map<string, GuidanceDefinition>();
let changed = 0, occurrences = 0;
async function replaceGenerated(file: string, value: string, expected: string) {
  const temp = `${file}.guidance-${randomUUID()}.tmp`;
  await writeFile(temp, value, { flag: 'wx' });
  if (await readFile(file, 'utf8') !== expected) throw new Error(`Source changed during guidance generation: ${file}; staged output retained at ${temp}`);
  await rename(temp, file);
}
for (const name of files) {
  const file = `src/${name}`, original = await readFile(file, 'utf8');
  const instrumented = instrumentGuidanceSource(original, file);
  if (instrumented.source !== original) { changed++; if (write) await replaceGenerated(file, instrumented.source, original); }
  const candidates = write && instrumented.source !== original ? scanGuidanceSource(instrumented.source, file) : instrumented.candidates;
  for (const c of candidates) {
    // Static tool contracts/policies have an explicit runtime projection.
    const projection = c.kind === 'prose' && c.parts.length === 1 && (/-tools\.ts$/.test(name) || ['createServer.ts', 'wiki-policy.ts', 'endpoint-registry.ts', 'organization.ts', 'research-templates.ts', 'community-participation-activities.ts', 'continuity-understanding-model.ts', 'knowledge-application-model.ts', 'knowledge-investigation-model.ts', 'knowledge-synthesis-model.ts'].includes(name));
    const binding = c.wrapped && !c.reason ? 'call' : projection ? 'projection' : 'pending';
    const old = definitions.get(c.id);
    if (old && (old.template !== c.template || JSON.stringify(old.parts) !== JSON.stringify(c.parts))) throw new Error(`Conflicting guidance ID ${c.id}`);
    if (old) { old.sources.push({ file, line: c.line }); if (binding !== 'pending') old.binding = binding; }
    else definitions.set(c.id, { id: c.id, kind: c.kind, template: c.template, parts: c.parts, binding, sources: [{ file, line: c.line }] });
    occurrences++;
  }
}
definitions.set('guid-server-instructions', { id: 'guid-server-instructions', kind: 'prose', template: MCPVAULT_SERVER_INSTRUCTIONS, parts: [MCPVAULT_SERVER_INSTRUCTIONS], binding: 'connection', sources: [{ file: 'src/wiki-policy.ts', line: 38 }] });
const entries = [...definitions.values()].sort((a, b) => a.id.localeCompare(b.id));
const target = 'src/guidance-defaults.generated.ts';
const generated = '// Generated by scripts/guidance-build.ts. Do not edit by hand.\nimport type { GuidanceDefinition } from \'./guidance-catalog.js\';\nexport const GUIDANCE_DEFINITIONS: GuidanceDefinition[] = ' + JSON.stringify(entries, null, 2) + ';\n';
if (write) await replaceGenerated(target, generated, await readFile(target, 'utf8'));
if (check && (changed || (await readFile(target, 'utf8')).replaceAll('\r\n', '\n') !== generated)) throw new Error('Guidance source/catalog drift: run npm run guidance:generate, review changes, and rebuild.');
console.log(JSON.stringify({ entries: entries.length, occurrences, sourceFilesChanged: changed, bindings: Object.fromEntries(['call', 'projection', 'connection', 'pending'].map(b => [b, entries.filter(d => d.binding === b).length])), coverage: 'Explicit prose properties, prose arrays and Error/TypeError/RangeError constructors only; not a claim that arbitrary text concatenations or generated documents are migrated.' }));
