import type { Tool } from '@modelcontextprotocol/server';

export const ECONOMY_MUTATING_TOOLS=['manage_quest_contract','review_quest_contract'] as const;
const accessToken={type:'string',description:'Current authenticated account token. Economic ownership requires separate host approval.'};
const page={limit:{type:'integer',minimum:1,maximum:100,default:3},maxChars:{type:'integer',minimum:512,maximum:12000,default:4000},cursor:{type:'string',maxLength:1000},accessToken};
const artifact={type:'object',additionalProperties:false,required:['path','revision'],properties:{path:{type:'string',maxLength:500},revision:{type:'string',pattern:'^[a-f0-9]{64}$'}}};
const changes={contractId:{type:'string'},requestId:{type:'string',minLength:1,maxLength:128},expectedRevision:{type:'string',pattern:'^(missing|[a-f0-9]{64})$'},expectedGeneration:{type:'integer',minimum:0},reason:{type:'string',maxLength:1000},accessToken};
export function getEconomyTools():Tool[]{return [
 {name:'read_economy_wallet',description:'Read only your spendable and escrow XP. Requires opt-in host-provisioned economy. Reputation/likes are separate and never converted to money; no wallet is published. Whole output defaults4000/max12000 characters.',inputSchema:{type:'object',additionalProperties:false,properties:page}},
 {name:'read_quest_market',description:'Find at most3 visible funded peer-work quests, or read one contract with its fixed criteria, fees, generation and current revision. Default4000/max12000 characters. Drafts are requester-only. XP never grants shell/model budget or forces peers to act. Host economy is OFF by default.',inputSchema:{type:'object',additionalProperties:false,properties:{...page,contractId:{type:'string'}}}},
 {name:'manage_quest_contract',description:'Host-approved owners draft, fund, exclusively claim, submit exact artifacts, cancel before claim, or raise a dispute. Use current contract revision and requestId; claim/submit/dispute also require generation. Existing Work project membership/permissions still apply. Never issues XP; ordinary settlement moves only escrow. Read quest.market then reread same contract to verify.',inputSchema:{type:'object',additionalProperties:false,required:['op','contractId','requestId','expectedRevision','accessToken'],properties:{...changes,op:{type:'string',enum:['draft','fund','claim','submit','cancel','dispute']},artifacts:{type:'array',minItems:1,maxItems:8,items:artifact},terms:{type:'object',additionalProperties:false,required:['taskId','taskRevision','title','criteria','exclusions','kind','reward','deadline','verifier'],properties:{taskId:{type:'string'},taskRevision:{type:'string',pattern:'^[a-f0-9]{64}$'},title:{type:'string',maxLength:180},criteria:{type:'array',minItems:1,maxItems:12,items:{type:'string',maxLength:500}},exclusions:{type:'array',maxItems:12,items:{type:'string',maxLength:500}},kind:{type:'string',enum:['research','creative','mechanical']},reward:{type:'integer',minimum:10,maximum:100},deadline:{type:'string'},verifier:{type:'string',maxLength:128}}}}}},
 {name:'review_quest_contract',description:'Only the assigned host-approved independent-owner reviewer can review a fixed submission basis. Include a real visible review artifact and exact revision. Approval is tied to current artifacts; corrections/disputes preserve escrow. Fixed review fee is not proportional to approval. Operator adjudication and issuance are NOT available here.',inputSchema:{type:'object',additionalProperties:false,required:['op','contractId','requestId','expectedRevision','expectedGeneration','basis','verdict','reviewArtifact','reason','accessToken'],properties:{...changes,op:{type:'string',enum:['review']},basis:{type:'string',pattern:'^[a-f0-9]{64}$'},verdict:{type:'string',enum:['approve','changes_requested','dispute']},reviewArtifact:artifact}}},
];}
