import { afterEach, expect, test } from 'vitest';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { FileSystemService } from './filesystem.js';
import { ScopeAccessPolicy } from './scope-access.js';
import type { ScopePrincipal } from './scope-auth.js';
import { LayeredMemoryService } from './layered-memory.js';
import { RetrievalService } from './retrieval-service.js';
import { SearchService } from './search.js';
import { CollaborationService } from './scopes.js';
import { SemanticSearchService } from './semantic-search.js';
import { PathFilter } from './pathfilter.js';
let root: string;
afterEach(async () => { if (root) await rm(root, { recursive: true, force: true }); });
test('explicit user memory joins colleagues of one user without broadening personal memory', async () => {
  root = await mkdtemp(join(tmpdir(), 'enterprise-memory-'));
  const fs = new FileSystemService(root); const search = new SearchService(root);
  const access = new ScopeAccessPolicy({ commandCenterId: 'acme', enterprise: { mode: 'company', realmId: 'acme' } });
  const semantic = new SemanticSearchService(root, new PathFilter(), access);
  const service = new LayeredMemoryService(fs, new RetrievalService(search, new CollaborationService(fs, search), semantic, access, fs), access);
  const actor: ScopePrincipal = { accountId: 'a', userId: 'u', agentId: 'network', modelId: 'codex', role: 'agent', commandCenterId: 'acme', enterprise: { realmId: 'acme', mode: 'company', runtimeId: 'local', sharedMemoryEnabled: true } };
  await fs.writeNote({ path: '_scopes/users/u/SharedMemory/Preference.md', content: 'Use concise Korean.', frontmatter: { memory_role: 'core' } });
  await fs.writeNote({ path: '_scopes/users/other/SharedMemory/Secret.md', content: 'unrelated-user-secret', frontmatter: { memory_role: 'core' } });
  await fs.writeNote({ path: '_scopes/users/u/OldHostSecret.md', content: 'host-only-secret', frontmatter: { memory_role: 'core' } });
  const shared = await service.read('brief', { principal: actor, scope: 'user', semantic: false } as any);
  expect(JSON.stringify(shared)).toContain('concise Korean');
  expect(JSON.stringify(shared)).not.toContain('secret');
  const personal = await service.read('brief', { principal: actor, semantic: false });
  expect(JSON.stringify(personal)).not.toContain('concise Korean');
  await expect(service.read('brief', { scope: 'user', semantic: false } as any)).rejects.toThrow(/user|shared|provision/i);
});
