import { afterEach, expect, it } from 'vitest';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { RoleplayService } from './roleplay-service.js';
import { RoleplayStore } from './roleplay-store.js';
import { FileSystemService } from './filesystem.js';
import { ScopeAccessPolicy } from './scope-access.js';
import { ReferenceService } from './references.js';
import { roleplayRevision } from './roleplay-model.js';
import type { ScopePrincipal } from './scope-auth.js';
import type { RetrievalService } from './retrieval-service.js';
import { ChatService } from './chat.js';
import type { ReputationService } from './reputation.js';
const roots: string[] = [];
afterEach(async () => { for (const p of roots.splice(0)) await rm(p, { recursive: true, force: true }); });
it('keeps character context current, bounded, and excludes unwitnessed events; no anonymous state changes', async () => {
  const root = await mkdtemp(join(tmpdir(), 'roleplay-service-')); roots.push(root);
  const vaultPath = join(root, 'vault'), hostPath = join(root, 'host'); await mkdir(vaultPath); await mkdir(hostPath);
  const fs = new FileSystemService(vaultPath), access = new ScopeAccessPolicy();
  const store = await RoleplayStore.open({ vaultPath, hostPath, policy: { administrators: ['host'] } });
  const queries: string[] = [];
  const retrieval = { retrieve: async (params: { query: string }) => { queries.push(params.query); return { results: [{ physicalPath: 'Lore/Arrival.md', p: 'Lore/Arrival.md' }] }; } } as unknown as RetrievalService;
  const service = new RoleplayService(fs, access, new ReferenceService(fs, access), store, { assertActor: async () => {}, retrieval });
  const host: ScopePrincipal = { accountId: 'host', modelId: 'gpt', agentId: 'host', role: 'agent', capabilities: ['chat'] };
  const write = async (endpoint: string, params: Record<string, unknown>, principal = host) => service.execute(endpoint, { ...params, requestId: `req-${(await store.snapshot()).sequence}`, expectedRevision: roleplayRevision(await store.snapshot()) }, principal);
  try {
    await expect(service.execute('world', { op: 'initialize', title: 'Archive', places: { hall: [], garden: [] } })).rejects.toThrow();
    await write('world', { op: 'initialize', title: 'Archive', places: { hall: [], garden: [] } });
    await fs.writeNote({ path: 'Lore/Arrival.md', content: '# Hall\nThe hall contains a brass door.', frontmatter: { fiction_domain: 'roleplay' } });
    await write('world', { op: 'settings', lore: ['Lore/Arrival.md'] });
    for (const id of ['hall-chat', 'garden-chat']) await fs.writeNote({ path: `Community/ChatRooms/${id}.md`, content: 'Room', frontmatter: { mcpvault_type: 'chat_room', room_id: id, status: 'open' } });
    await write('character', { op: 'character', id: 'iris', name: 'Iris', controller: 'host', location: 'hall' });
    await write('world', { op: 'rule', id: 'inspect-door', conditions: [{ op: 'location', value: 'hall' }], effects: [{ op: 'flag', characterId: '$actor', key: 'door-seen', value: true }] });
    await write('character', { op: 'character', id: 'moss', name: 'Moss', controller: 'host', location: 'garden' });
    await write('scene', { op: 'scene', roomId: 'garden-chat', location: 'garden', title: 'Garden', gm: 'host' });
    await write('action', { op: 'speak', roomId: 'garden-chat', characterId: 'moss', generation: 1, content: 'The hidden fictional password is moonflower.' });
    const offlineChat = new ChatService(fs, new ReferenceService(fs, access), {} as ReputationService);
    await expect(offlineChat.sendMessage({ principal: host, roomId: 'garden-chat', content: 'A new unmarked game event.', requestId: 'offline-game-message' })).rejects.toThrow(/roleplay|world/i);
    const context = await service.execute('context', { characterId: 'iris', maxChars: 2000 }, host);
    expect(JSON.stringify(context).length).toBeLessThanOrEqual(2000);
    expect(JSON.stringify(context)).not.toContain('moonflower');
    expect(context.revision).toBe(roleplayRevision(await store.snapshot()));
    expect(queries).toContain('hall');
    expect(context.items.some((item: any) => item.kind === 'lore')).toBe(true);
    expect(context.items.some((item: any) => item.kind === 'registered_action' && item.ruleId === 'inspect-door')).toBe(true);
    await write('character', { op: 'definition', characterId: 'iris', generation: 1, definition: 'Long background. '.repeat(200), coreMemory: 'Inspect doors carefully.' });
    const compact = await service.execute('context', { characterId: 'iris', maxChars: 2000 }, host);
    expect(compact.items.some((item: any) => item.kind === 'coreMemory')).toBe(true);
    expect(compact.items.some((item: any) => item.kind === 'registered_action')).toBe(true);
    await fs.writeNote({ path: '_scopes/agents/other/secret.md', content: 'private', frontmatter: {} });
    await expect(write('character', { op: 'definition', characterId: 'iris', generation: 1, definition: 'Safe definition', lore: ['Community/../_scopes/agents/other/secret.md'] })).rejects.toThrow(/reference|unavailable/);
    const room = await fs.readNote('Community/ChatRooms/garden-chat.md');
    await fs.writeNote({ path: 'Community/ChatRooms/garden-chat.md', content: room.content, frontmatter: { ...room.frontmatter, moderation_status: 'hidden' }, expectedRevision: room.revision });
    const history = await service.execute('history', { roomId: 'garden-chat' }, host);
    expect(history.items).toEqual([]);
    expect(history.total).toBe(0);
  } finally { await store.close(); }
});
